### ISSUE TITLE
Add a notice informing users that ports are not stripped

### ISSUE THREAD

**Issue by Rooni** [un33k/django-ipware#103]
As of now this package is broken for azure hosted applications (and probably others) and will always return the `REMOTE_ADDR` ip as fallback.

For `python-ipware` this does work properly.

If this won't be fixed in this package as stated [here](https://github.com/un33k/django-ipware/pull/89#issuecomment-1352352351), please at least add a notice or warning somewhere that `get_client_ip()` won't return any ips that contain ports, or archive this repo in favor of `python-ipware`.

**Comment by un33k** [comment]
fixed via:  https://github.com/un33k/django-ipware/pull/106
