### ISSUE TITLE
README mentions IPWARE_META_PRECEDENCE_LIST instead of IPWARE_META_PRECEDENCE_ORDER

### ISSUE THREAD

**Issue by HageMaster3108** [un33k/django-ipware#13]
The README.md mentions IPWARE_META_PRECEDENCE_LIST - shouldn't this be IPWARE_META_PRECEDENCE_ORDER?

**Comment by un33k** [comment]
Thanks for the fix. https://github.com/un33k/django-ipware/pull/14
