### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by vladir** [un33k/django-ipware#17]
I'm thinking into upgrade a project that uses django-ipware very soon to Django 1.9. Is this already supported? Thanks in advance.

**Comment by AlexRiina** [comment]
On travis-ci, it looks like it passes against django==1.9

https://travis-ci.org/un33k/django-ipware/jobs/99499583

**Comment by vladir** [comment]
Thanks a lot @AlexRiina :), good to know that

**Comment by un33k** [comment]
Yeah, as @AlexRiina noted, it's best to look at the .travis.yml for compatibility.  Ipware works with almost all version of Django, however, the tests only cover the officially supported version of Django.
