### ISSUE TITLE
Clarification of "publicly accessible"

### ISSUE THREAD

**Issue by DanielStevenLewis** [un33k/django-ipware#20]
Could you please clarify what you mean by "publicly accessible"? For example if I have an application server running on a different physical server than my web server is running on, and the application server is only accessible from the web server, does the application server count as publicly accessible? It's not directly accessible by the public, but information from it is publicly accessible via the web server. Does it still count as a publicly accessible server for the purposes of using ipware?

**Comment by un33k** [comment]
IPware is a server-level app not a data-level.  If you can ping your WEB SERVER from anywhere on the internet then that server is publicly accessible.   

Val
