### ISSUE TITLE
using ipware in model pre_save

### ISSUE THREAD

**Issue by anuj9196** [un33k/django-ipware#30]
I have a model in my project without view which creates a new associated record on `post_save` of parent model.

I used

```
from django.urls import reverse
from ipware.ip import get_real_ip

class ShortUrlVisitLogs(models.Model):
     shorturl = models.ForeignKey(ShortUrl, on_delete=models.CASCADE, blank=True)
     ip_address = models.CharField(max_length=225, blank=True, null=True)
     visit_time = models.DateTimeField(auto_now_add=True)

@receiver(pre_save, sender=ShortUrlVisitLogs)
def pre_save_short_url_visit_logs(sender, instance, *args, **kwargs):
    instance.ip_address = get_real_ip(request)
```

Since this does not require any view. I want to use `get_real_ip(request)` in the model `pre_save` receiver as shown above.

But this is returning error
```
module 'django.http.request' has no attribute 'META'
```

**Comment by un33k** [comment]
A valid Django `request` object is get_real_ip()'s requirement. Best is to get the user's IP address in the very first request and store it in user's session or DB. Then you can use it wherever you want.

StackOverflow is the right place for usage & how-to questions.
