### ISSUE TITLE
Option to configure the number of proxies

### ISSUE THREAD

**Issue by aleksihakli** [un33k/django-ipware#33]
Hi, I think there should be an option to configure the number of trusted proxies. The `django-axes` module switched over to this module and previously had configuration in place to allow configuring proxy count as implemented [in `django-axes` #225](https://github.com/jazzband/django-axes/pull/225) and I think it would be a nifty feature here as well.

I understand that this package seems to aim more on efficiency and usability than security and filtering out noise and that resolving IPs is a best-effort case, but adding a simple check for number of proxies shouldn't be too hard, if it is deemed useful.

[Here is the some ongoing discussion about this] (https://github.com/jazzband/django-axes/issues/286) for reference.

**Comment by un33k** [comment]
@aleksihakli as per my explanation [here](https://github.com/jazzband/django-axes/issues/286), nothing stops a hacker to set up additional proxies to match the proxy count.

Please provide a use case that we need a proxy count on top of the already supported trusted proxy list in order for me to include such a feature in the next release. thx.

**Comment by un33k** [comment]
Unofficial -- Look at the source code for get_client_ip()

**Comment by aleksihakli** [comment]
@un33k yeah, I thought of it more as a convenience feature, I'm aware that attackers can do DNS rebinding and proxy injection on the server end or just forge headers by hand in the client end. 

The case is indeed that I'm getting a ton of unwanted traffic on AWS with no proxies set at all in the request headers and want to discard that, and am using proxy count in a middleware to cut the unwanted noise, and think that this is useful for tracking bots and improperly configured clients. 

In Axes it's nice to also get notified of someone banging the authentication backend with improper requests :)

I think the 2.0 beta release looks good for the purpose and the trusted proxies approach is good for semi-static proxy IPs. It can be hard to figure out proxy IPs in elastic environments where load balancers have dynamically changing IP ranges, so the proxy count is more usable there.

**Comment by un33k** [comment]
Version [2.0](https://github.com/un33k/django-ipware) has Proxy Count support added.  Version 1.x is deprecated, however, I don't have any plans in removing the api.  Cheers
