### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by rtp-calpoly** [un33k/django-ipware#4]
Is this library compatible with Python 3?

**Comment by rtp-calpoly** [comment]
Taking a look at the requirements.txt changelog, it looks like it is; but I prefer to ask just in case there is any non-compatibility. Thank you in advance.

**Comment by un33k** [comment]
What you can do in situations like this, is to click on the pass rate image. It will take you to Travis CI and you can see if py3 tests are currently passing.

**Comment by rtp-calpoly** [comment]
Ok, thanks for the tip! It looks like it is using Python 3.4.1 (as of today) for passing the tests.
