### ISSUE TITLE
IPv6 address routability

### ISSUE THREAD

**Issue by Karimerto** [un33k/django-ipware#52]
All (other than specifically fc00:) IPv6 ULA addresses are incorrectly identified as globally routable. Not really a big issue, but an annoyance regardless.

I would suggest adding the use of `ipaddress` or similar library for checking the actual addresses. They would have to be written in proper CIDR notation, i.e. `fc00::/7` and checked with the library's functions. As an added benefit, the list of IPs in the `defaults.py` would be somewhat shorter.

I'd be happy to submit a patch if you think this is an idea you'd consider.

**Comment by un33k** [comment]
Do you have a link to the specs?

**Comment by Karimerto** [comment]
Specs are the same as in your documentation: https://en.wikipedia.org/wiki/Reserved_IP_addresses. But what I mean is using https://docs.python.org/3/library/ipaddress.html for detecting whether an address actually belongs to a given subnet. I created a version which does this and it seems to work nicely. I also added a couple of tests to check for more private IP addresses.

**Comment by un33k** [comment]
@Karimerto  I am looking forward to your PR. Please have in mind that we still need to support py 2.7. As the link you provided is only in py 3.

Alternatively, we can pin use `python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*',` and make the next version py 3.0 only.

**Comment by Karimerto** [comment]
Actually the same `ipaddress` library exists in both python versions, 2 and 3. I forked a copy of this and pushed the necessary changes. However it currently supports only python 3, as python 2's version of `ipaddress` library wants the string to be unicode (as in `u'something'`). I'll see if I can easily create something that'll support both 2 and 3.

**Comment by un33k** [comment]
I have looked at your work and it looks great. If you can make it fallback on what we have now for 2.7, it would be a great PR. Thx

**Comment by un33k** [comment]
@Karimerto  django-ipware is on its way to being deprecated.

With that said, I have a python package that is going to replace it.

Have a look at [python-ipware](https://github.com/un33k/django-ipware) and if works for you switch to it.

Feedback is welcomed.
