### ISSUE TITLE
Document Django middleware

### ISSUE THREAD

**Issue by skorokithakis** [un33k/django-ipware#53]
I see in #36 that a middleware has been implemented, could this be documented? It's very useful but I didn't see it anywhere in the README.

**Comment by un33k** [comment]
@skorokithakis django-ipware is on its way to being deprecated.

With that said, I have a python package that is going to replace it.

Have a look at [python-ipware](https://github.com/un33k/django-ipware) and if works for you switch to it.

Feedback is welcomed.
