### ISSUE TITLE
Cannot run pytest tests after installing django-ipware

### ISSUE THREAD

**Issue by GeorgianBadita** [un33k/django-ipware#56]
Hi, after installing django-ipware package I cannot run pytest tests, here is a stacktrace of the error

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/main.py", line 187, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/config/__init__.py", line 820, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_sugar.py", line 176, in pytest_configure
INTERNALERROR>     sugar_reporter = SugarTerminalReporter(standard_reporter)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_sugar.py", line 214, in __init__
INTERNALERROR>     self.writer = self._tw
INTERNALERROR> AttributeError: can't set attribute

Packages installed:
auth0-python==3.9.1       # via -r requirements.in
boto3==1.12.18            # via -r requirements.in
botocore==1.15.18         # via boto3, s3transfer
certifi==2019.11.28       # via requests
cffi==1.14.0              # via cryptography
chardet==3.0.4            # via requests
cryptography==2.8         # via -r requirements.in, pyjwt
django-admin-display==1.1.0  # via -r requirements.in
django-constance[database]==2.6.0  # via -r requirements.in
django-cors-headers==3.2.1  # via -r requirements.in
django-filter==2.2.0      # via -r requirements.in
django-grappelli==2.14.1  # via -r requirements.in
django-mysql==3.3.0       # via -r requirements.in
django-picklefield==2.1.1  # via django-constance
django-storages==1.9.1    # via -r requirements.in
django==2.2.7             # via -r requirements.in, django-cors-headers, django-filter, django-mysql, django-picklefield, django-storages
djangorestframework==3.10.3  # via -r requirements.in
docutils==0.15.2          # via botocore
faker==4.0.1              # via -r requirements.in
gunicorn==20.0.4          # via -r requirements.in
idna==2.9                 # via requests
jmespath==0.9.5           # via boto3, botocore
mysqlclient==1.4.6        # via -r requirements.in
phonenumbers==8.11.5      # via -r requirements.in
pillow==7.0.0             # via -r requirements.in
pycountry==19.8.18        # via -r requirements.in
pycparser==2.20           # via cffi
pyjwt[crypto]==1.7.1      # via -r requirements.in
python-dateutil==2.8.1    # via botocore, faker
pytz==2019.3              # via django
redis==3.4.1              # via -r requirements.in
requests==2.23.0          # via auth0-python
s3transfer==0.3.3         # via boto3
six==1.14.0               # via cryptography, django-grappelli, python-dateutil
sqlparse==0.3.1           # via django
text-unidecode==1.3       # via faker
urllib3==1.25.8           # via botocore, requests
whitenoise==5.0.1         # via -r requirements.in

**Comment by un33k** [comment]
Your log indicates that you have not installed `django-ipware`. Pls double heck.

**Comment by GeorgianBadita** [comment]
> Your log indicates that you have not installed `django-ipware`. Pls double heck.

Those are the other packages, without django-ipware

**Comment by GeorgianBadita** [comment]
Solved the issue. The problem is that SugarTerminalReporter is not compatible yet with pytest  >= 5.4.0
