### ISSUE TITLE
Is there a way to always get ipv4?

### ISSUE THREAD

**Issue by dhsdshdhk** [un33k/django-ipware#59]
For my use case, I need the ipv4, but django-ipware keeps giving me ipv6. Is there any way to get ipv4 only?

Thank you.

edit: I figured my question doesn't make sense. I had to disable ipv6 in my website.

**Comment by un33k** [comment]
No, unless the IPv4 was wrapped in IPv6. 

django-ipware is on its way to being deprecated.

With that said, I have a python package that is going to replace it.

Have a look at [python-ipware](https://github.com/un33k/django-ipware) and if works for you switch to it.

Feedback is welcomed.
