### ISSUE TITLE
Why am I seeing this ?

### ISSUE THREAD

**Issue by Sonic122** [un33k/django-ipware#6]
![gcdu0bb-g6au85asdtjhw5vh_ez-gbqmb7hszdm-tra](https://cloud.githubusercontent.com/assets/11913414/7106639/bc142ea2-e150-11e4-885d-23e79e3d9870.jpg)

**Comment by un33k** [comment]
That means the requests that you are passing to get_ip doesn't have a META attribute. It should.
I would start by looking at where the request is passed in to get_ip(). Examine the request before sending it down to get_ip() and if it doesn't have META, then get_ip() cannot extract any meta info.
