### ISSUE TITLE
get_client_ip returns the wrong value

### ISSUE THREAD

**Issue by elkd** [un33k/django-ipware#62]
In the beginning, the function was working perfectly but all of the sudden like 3 days ago things just changed. when I query it returns the private IP address of the network load balancer. My config is like 
client -> Network LB -> Application LB -> Nginx -> Django server

I just call the function with default values, I didn't pass the arguments like proxy count or trusted IPs. Are these values a must or it is the issue with LB configuration?

 Any idea, please help?

**Comment by un33k** [comment]
@elkd I do recommend to;
1- `pip uninstall django-ipware` and `pip install django-ipware`.  If that solves the problem, then great if not cont. w/ step 2
2- If it worked, and it is not working now, if the ipware version is not changed, then look at the network LB for misconfiguration
3- If you don't have access to the upstream `network LB` config, then you are out of luck .. 

`ipware` can show you what it receives with default values.  If the bad ip or spoofed IP is passed down the chain, then you may not be able to do anything about it.

**Comment by elkd** [comment]
Thank you so much for your prompt response. The issue is with the Network Load Balancer, I'll close the issue for now as I communicate with the infra guys. If the server still misbehaves I'll re-open the issue.
