### ISSUE TITLE
Pypi description completely empty

### ISSUE THREAD

**Issue by WoLpH** [un33k/django-ipware#68]
A bit of a boring page like this:
![image](https://user-images.githubusercontent.com/270571/111891051-c168ec00-89ef-11eb-91df-64dfb6ff1954.png)

You should be able to upload your regular readme to PyPI :)
https://pypi.org/project/django-ipware/

**Comment by un33k** [comment]
@WoLpH It should've minimally had the description from the `setup.py` - `description = "A Django utility application that returns client's real IP address"` but it doesn't.

Pypi used to handle README.md, but it doesn't anymore it seems.  
I'll have a look on the next push.

**Comment by un33k** [comment]
A PR on would be nice ...

**Comment by un33k** [comment]
Moved with twine and fixed the readme not being sent up. 
https://github.com/un33k/django-ipware/issues/68
