### ISSUE TITLE
1.0.0.0/8 and 2.0.0.0/8

### ISSUE THREAD

**Issue by mknecht** [un33k/django-ipware#7]
You list the 1.0.0.0/8 and 2.0.0.0/8 spaces as private by default. That's [not true anymore](http://en.wikipedia.org/wiki/List_of_assigned_/8_IPv4_address_blocks#List_of_assigned_.2F8_blocks_to_the_Regional_Internet_Registries) — they have been [opened up](http://arstechnica.com/business/2010/06/addresses-at-the-bottom-of-the-ipv4-barrel-not-so-pure/) for use around 2010.

Currently, we're getting errors cuz we cannot get the IP of some visitors, with 1.38… prefix. While of course I can override the setting, it'd be more convenient (and helpful for others) to drop those two ranges from the defaults list.

**Comment by un33k** [comment]
Thanks for the info. Please overwrite the settings for your setup for now
till the next release cycle.

**Comment by un33k** [comment]
Please upgrade to version 1.1.0 and enjoy!

**Comment by mknecht** [comment]
Huh, cheers! :)
