### ISSUE TITLE
Release this package with Django 3.2 support

### ISSUE THREAD

**Issue by Jawayria** [un33k/django-ipware#72]
Hey, we are working on upgrading edX codebase to Django 3.2. This package is being used in the codebase but it isn't yet released with Django 3.2 support. Kindly consider releasing it with Django 3.2 support.
Thanks

**Comment by un33k** [comment]
@Jawayria this package doesn't depend on anything specific in Django. It should work for all versions, even if the test is not there yet. 

The tests will follow - PR welcomed!

**Comment by un33k** [comment]
@Jawayria django-ipware is on its way to being deprecated.

With that said, I have a python package that is going to replace it.

Have a look at [python-ipware](https://github.com/un33k/django-ipware) and if works for you switch to it.

Feedback is welcomed.
