### ISSUE TITLE
Looking for 1-2 contributors to de-risk the project as it is now used by many projects

### ISSUE THREAD

**Issue by un33k** [un33k/django-ipware#73]
django-ipware is now used by many projects and many major companies. As such, it would be smart to have more than one person with admin access to the project, especially, in times of pandemics.

If you would like to contribute in de-risking django-ipware and posses solid python background, with keen interests in supporting open source projects for the benefit of many; - send me an email with links to a few python projects you are maintaining.

I will select two individuals and promote them to admin level.

I'd appreciate your consideration.

Val

**Comment by sinwoobang** [comment]
I have sent you an email :)

**Comment by tazahmd** [comment]
I have emailed you .

**Comment by danizen** [comment]
I am interested.  I recently discovered django-ipware, have contributed pulls to django and django-cas-ng, and have developed similar software within our own uber package (which I do not believe to be as solid as django-ipware - we only look at `X-Forwarded-For`, a local `X-Forwareded-For-IPV6` sent by our f5 LTM, and `REMOTE_ADDR`.

**Comment by un33k** [comment]
@danizen Thank you.

I am looking for someone to convert djang-ipware to match this package that I wrote for NodeJs.?

https://github.com/neekware/fullerstack/blob/main/libs/nax-ipware/README.md

Right now, I am looking for a clean rewrite.  Is this something of interest to you @danizen ?
