### ISSUE TITLE
setup.py license classifier does not match LICENSE

### ISSUE THREAD

**Issue by jvalleroy** [un33k/django-ipware#74]
setup.py says the license is "Apache Software License", but LICENSE says it is "MIT License".

**Comment by sinwoobang** [comment]
@un33k It would be better to be confirmed.

**Comment by un33k** [comment]
@sinwoobang MIT is the licensing.  Could you push a PR with the following:

`'License :: OSI Approved :: MIT License',`

**Comment by sinwoobang** [comment]
Thank you for the report. It is reflected.
