### ISSUE TITLE
Precedence order is not regarded when all IPs are not routable

### ISSUE THREAD

**Issue by tahajahangir** [un33k/django-ipware#76]
With current logic in `ips.py`, the code returns **last** (instead of first) not-routable IP if all IPs are not routable.

**Comment by un33k** [comment]
@tahajahangir Please tell us more about your setup to better visualize your needs.

**Comment by tahajahangir** [comment]
Suppose following sample setup:
```
CLIENT [IP: 10.10.11.11]   <-> NGINX [IP: 192.168.1.100] <-> SERVER [IP: 192.168.1.150]
```
When actual client IP is a non-routable IP (as abow), the module will return `192.168.1.100` as client-ip.

**Comment by un33k** [comment]
I think we might need to update [ip.py](https://github.com/un33k/django-ipware/blob/master/ipware/ip.py) to reflect the login in the typescript equivalent package.

https://github.com/neekware/fullerstack/blob/main/libs/nax-ipware/README.md

Could you take a look at [ipware.ts](https://github.com/neekware/fullerstack/blob/51f341c9ab4683e7ea7621ee5074188531d454de/libs/nax-ipware/src/lib/ipware.ts#L98) and do the same thing here?

This package will remain unchanged, till someone ports the `ts` version over.
