### ISSUE TITLE
Suggestion - define default settings value

### ISSUE THREAD

**Issue by danizen** [un33k/django-ipware#78]
In https://github.com/un33k/django-ipware/blob/cea65823c07a87ce477fee31f3302c96efaf5a24/ipware/defaults.py#L8, django-ipware defines a local constant which leaves it unclear to Django users what the default setting is without reading the code.

[django-cas-ng](https://github.com/django-cas-ng/django-cas-ng/blob/master/django_cas_ng/__init__.py) has a different approach, but I would move django-cas-ng's settings to the apps module.

Suggesting similar so that `settings.IPWARE_META_PRECEDENCE_ORDER` will be defined with default value if it is not set when app is readied by Django.

**Comment by un33k** [comment]
Not true!  

People who want to read instructions can do that by looking at the readme. https://github.com/un33k/django-ipware#precedence-order

Those who are coders and want to look around should see that 

```python 
IPWARE_META_PRECEDENCE_ORDER = getattr(settings, ...)
```

means get the constant from the global `settings.py`, if not found, then define a default value. 

So, users have the power to set their own precedence order.

Those who want per call precedence orders can also pass those in, on each call, as per the link above.

**Comment by un33k** [comment]
@danizen django-ipware is on its way to being deprecated.

With that said, I have a python package that is going to replace it.

Have a look at [python-ipware](https://github.com/un33k/django-ipware) and if works for you switch to it.

Feedback is welcomed.
