### ISSUE TITLE
Security risks of the default settings

### ISSUE THREAD

**Issue by vdboor** [un33k/django-ipware#8]
The default `IPWARE_META_PRECEDENCE_ORDER` settings cause django-ipware to check for various types of headers by default. However, not all headers may be there, or get filtered through the webserver.

In a standard setup (apache+mod_wsgi or nginx+uwsgi), only `REMOTE_ADDR` applies and needs to be read. Since there are many other headers in `IPWARE_META_PRECEDENCE_ORDER`, I could pass any of these to fake an IP address:
* `X-Forwarded-For`
* `Client-IP`
* `X-Real-IP`
* `X-Forwarded`
* `X-Cluster-Client-IP`
* `Forwarded-For`
* `Forwarded`
* `Via`

I'd strongly recommend reducing `IPWARE_META_PRECEDENCE_ORDER` to just `REMOTE_ADDR` and let users configure their system explicitly when they use a forwarding http server in their setup.

**Comment by un33k** [comment]
The purpose of this module is to make the best attempt to find the private or a routable IP address of the client while keeping it DRY, and acknowledging that IP addresses can be spoofed and there is no way to avoid that.

The security of no web-stack should rely on this module and If `ipware` is used with the security mindset, then `IPWARE_META_PRECEDENCE_ORDER` should be overwritten as per specific setup requirements.

**Comment by vdboor** [comment]
>  The security of no web-stack should rely on this module

Agreed.

I would opt to mention this clearly in the README. The default just works, but no more then unpacking a wifi router and use it without reading instructions.

**Comment by un33k** [comment]
I would appreciate a pull request where a `Notice` is added to the README file regarding the security implication of the default behavior. I'll include it in the next release cycle.
