### ISSUE TITLE
Feature proposal: get IP address in list of IPs based on `ip_count`

### ISSUE THREAD

**Issue by sergei-maertens** [un33k/django-ipware#84]
First - thanks for this package & especially in our case the use of it in django-axes.

I have read #8 about this topic and I believe this proposal stays in line with the spirit of this project while giving some more control for advanced users.

Recently I've been looking into the expected and actual behaviour of these packages with regard to spoofing, especially in the context where we build and implement projects without having much control over the infrastructure where it's deployed and being able to ship with "safe" defaults as much as possible. Please keep this context in mind while I describe the feature.

Currently, if you specify `proxy_count` and this does not match the amount of ip addresses in the header value, then that header value is skipped from processing, ultimately leading to the detected IP being `None`.

E.g. with a Kubernetes ingress (reverse proxy) in front of an nginx reverse proxy in front of the django wsgi server, you have two reverse proxies in total (and a value of `proxy_count=1`). Given a client spoofing `X-Forwarded-For: 1.2.3.4`, the list of IP addresses seen in the request headers then turns up as `[1.2.3.4, real-ip, ingress-ip]` for `X-Forwarded-For` (with `Remote-Addr` being the nginx proxy ip). Because of the `proxy_count` mismatch (1 != 3 -1), the resulting IP address down the road is `None`. However, we *could* have grabbed `ips[-2]` based on `proxy_count` - `ips[-proxy_count - 1]` (for left-most ordering), which would have yielded the correct IP address in this situation.

This is also in line with how django-rest-framework treats `NUM_PROXIES`: https://github.com/encode/django-rest-framework/blob/master/rest_framework/throttling.py#L37

There are probably a number of edge with left-most/right-most ordering and peculiarities, but would you be open to the concept?

Edit - via the django-axes issue I also stumbled on #33, I think that makes it clear enough that the trusted proxies settings should be used instead.

**Comment by un33k** [comment]
@sergei-maertens django-ipware is on its way of being deprecated. 

With that said, I have a python package that is going to replace it. 

Have a look at [python-ipware](https://github.com/un33k/django-ipware) and if works for you switch to it.

Feedback is welcomed.
