### ISSUE TITLE
Django 1.5 compatibility

### ISSUE THREAD

**Issue by mhb11** [un33k/django-ipware#9]
@un33k : Hello, is this backwards compatible with Django 1.5 projects?

**Comment by un33k** [comment]
Tests are run against the supported version of Django only.

Have a look at the test matrix @ https://github.com/un33k/django-ipware/blob/master/.travis.yml

That doesn't mean that it won't work with 1.5. It is just not being verified any longer.

**Comment by mhb11** [comment]
Thanks
