### ISSUE TITLE
ipware ignoring precedence order

### ISSUE THREAD

**Issue by syserr0r** [un33k/django-ipware#96]
I've been banging my head against this all day, now I've been able to make a simple reproduction, can someone confirm if this behaviour is correct?

My understanding is that in all the cases below, apart from the last, the IP address should be `192.168.1.2` however this is clearly not the case.

Running version `django-ipware==5.0.0` inside a Docker container based on `python:3.11-slim`:

```python
from django.test import Client
from ipware import get_client_ip
client = Client()
r = client.get('/', QUERY_STRING="meta=1", REMOTE_ADDR="1.2.3.4", REMOTE_HOST="4.5.6.7", REMOTE_PORT=12345, SERVER_NAME="9.9.9.9", headers={'X-Forwarded-For': '192.168.1.2', 'Host': 'test-server'}).wsgi_request

get_client_ip(r, proxy_count=None, proxy_trusted_ips=None)
> ('1.2.3.4', True)

get_client_ip(r, proxy_count=None, proxy_trusted_ips=None, request_header_order=None)
> ('1.2.3.4', True)

get_client_ip(r, proxy_count=None, proxy_trusted_ips=None, request_header_order=['HTTP_X_FORWARDED_FOR',])
> ('192.168.1.2', False)

get_client_ip(r, proxy_count=None, proxy_trusted_ips=None, request_header_order=['HTTP_X_FORWARDED_FOR','REMOTE_ADDR'])
> ('1.2.3.4', True)

get_client_ip(r, proxy_count=None, proxy_trusted_ips=None, request_header_order=['REMOTE_ADDR','HTTP_X_FORWARDED_FOR'])
> ('1.2.3.4', True)
```

**Comment by syserr0r** [comment]
Thank-you for explaining that. My hands are slightly tied as I am using [django-axes](https://github.com/jazzband/django-axes) which relies on this package.

Is there any preference between IP ranges? In my actual deployment it is preferring 172.17.0.1 (the `REMOTE_ADDR`) over anything in 192.168.0.0/24 (the `HTTP_X_FORWARDED_FOR`)

While your explanation explains my reproduction, I don't think it explains preferring the above as they are both private IPs (unless I've missed something).

For now I have simply set the `request_header_order=['HTTP_X_FORWARDED_FOR']` as all requests come through a proxy.

**Comment by un33k** [comment]
you can raise a ticket with `django-axes` to upgrade to `python-ipware` directly.  For now, I am glad you have found a workaround.

**Comment by syserr0r** [comment]
Sounds like my best bet, and although my work-around for the local IP works, an `X-Forwarded-For` of `212.69.X.Y, 195.191.X.Y` returns `None` which seems wrong (some of our requests are through a second proxy, some are not).
